---
- name: Check if the Metasploit Framework is already installed
  ansible.builtin.stat:
    path: "{{ install_directory }}"
  register: msf_directory

- name: Install the Metasploit Framework
  block:
    - name: Download the Metasploit Framework installer
      ansible.builtin.get_url:
        # TODO: https://github.com/cisagov/ansible-role-metasploit/issues/6
        # Replace this installer script
        url: https://raw.githubusercontent.com/rapid7/metasploit-omnibus/{{ installer_version }}/config/templates/metasploit-framework-wrappers/msfupdate.erb
        dest: /tmp/msfinstall
        mode: 0755

    - name: Install the Metasploit Framework
      ansible.builtin.command:
        cmd: /tmp/msfinstall
        creates: "{{ install_directory }}"

    - name: Delete the Metasploit Framework installer
      ansible.builtin.file:
        path: /tmp/msfinstall
        state: absent
  when: not msf_directory.stat.exists
