---
- name: Download Metasploit Framework Installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb
    dest: /tmp/msfinstall
    mode: 0755

- name: Install Metasploit Framework
  ansible.builtin.command: /tmp/msfinstall

- name: Delete Metasploit Framework Installer
  ansible.builtin.file:
    path: /tmp/msfinstall
    state: absent
  become: no
  delegate_to: localhost
